name: Docker Builder

on:
  push:
    paths:
      - 'Dockerfile'
    branches:
      - 'master'
  schedule:
    # Run at 03:00am, once after every week, every month
    - cron: '0 3 7,14,21,28 1-12 ?'

jobs:

  build:

    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: fr3akyphantom
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      IMAGE_NAME: skadoosh

    steps:
    - uses: actions/checkout@v1.2.0

    - name: Bypass Build
      if: "contains(github.event.head_commit.message, '[skip ci]')"
      run: echo -en "Bypassing the main build, because the commit message contains - [skip ci]" && exit 0

    - name: Create & Push the tranSKadooSher Container
      if: "! contains(github.event.head_commit.message, '[skip ci]')"
      run: >-
        echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_USERNAME --password-stdin

        echo ".git" > .dockerignore

        docker build . --file Dockerfile
        --rm --force-rm --compress --no-cache=true --pull
        --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%S%Z"`
        --build-arg VCS_REF=`git rev-parse --short HEAD`
        --build-arg VCS_URL=`git remote get-url origin`
        --build-arg VERSION='1.0'
        --tag $DOCKER_USERNAME/$IMAGE_NAME:latest

        docker push $DOCKER_USERNAME/$IMAGE_NAME:latest

    - name: Refresh MicroBadger Metadata for Container Info
      if: "! contains(github.event.head_commit.message, '[skip ci]')"
      run: curl -X POST "https://hooks.microbadger.com/images/fr3akyphantom/skadoosh/o9fKNYwu31M9bV-2ZpxzOP1bMWc="
