name: Docker Builder

on:
  push:
    paths:
      - 'Dockerfile'
    branches:
      - 'master'
  workflow_dispatch:
  schedule:
    # Run at 03:00am, once after every week, every month
    - cron: '0 3 7,14,21,28 1-12 ?'

jobs:

  build:

    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: fr3akyphantom
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      IMAGE_NAME: skadoosh

    steps:
    - uses: actions/checkout@v2

    - name: Bypass Build
      if: "contains(github.event.head_commit.message, '[skip ci]')"
      run: echo -en "Bypassing the main build, because the commit message contains - [skip ci]" && exit 0

    - name: Create & Push the tranSKadooSher Container
      if: "! contains(github.event.head_commit.message, '[skip ci]')"
      run: >-
        echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_USERNAME --password-stdin

        echo ".git" > .dockerignore

        docker build . --file Dockerfile
        --rm --force-rm --compress --no-cache=true --pull
        --label org.label-schema.build-date=$(date -u +"%Y-%m-%dT%H:%M:%S%Z")
        --label org.label-schema.name="tranSKadooSHer"
        --label org.label-schema.description="Alpine based image usable for running tranSKadooSH Projects"
        --label org.label-schema.url="https://rokibhasansagar.github.io"
        --label org.label-schema.vcs-ref=$(git rev-parse --short HEAD)
        --label org.label-schema.vcs-url=$(git remote get-url origin)
        --label org.label-schema.vendor="Rokib Hasan Sagar"
        --label org.label-schema.version='1.0.1'
        --label org.label-schema.schema-version="1.0"
        --tag $DOCKER_USERNAME/$IMAGE_NAME:latest

        docker push $DOCKER_USERNAME/$IMAGE_NAME:latest

    - name: Refresh MicroBadger Metadata for Container Info
      if: "! contains(github.event.head_commit.message, '[skip ci]')"
      run: curl -X POST "https://hooks.microbadger.com/images/fr3akyphantom/skadoosh/o9fKNYwu31M9bV-2ZpxzOP1bMWc="
